export default {
  BASE_URL: "XXXX",
  GOOGLE_CLOUD_SERVICES_API_KEY: "XXXX",
  IMAGE_PATH_AWS:
    "XXXX",
  HEADER_COLOR: "#5D1049",
  HEADER_TINT_COLOR: "#fff",
  HEADER_TITLE_FONTWEIGHT: "500",
  SENTRY_DSN: "XXXX",
};
